name: build-and-package-alpha

on:
  push:
    branches:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: npm install

      - name: Test
        run: |
          npm run lint
          npm test

      - name: publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}

      - name: Build
        run: npm run build

      - name: Set version
        run: |
          npm version --no-git-tag-version $(git describe --abbrev=0 --tags)-alpha.$(git rev-parse --short=6 ${{ github.sha }})

      - run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
