name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm v7
        run: |
          npm i -g npm@7

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set version
        run: |
          npm version --no-git-tag-version $(git describe --abbrev=0 --tags)

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}